// <auto-generated />
using System;
using FlowFocus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowFocus.Data.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20260103202752_RemoveIsSystemPriorities")]
    partial class RemoveIsSystemPriorities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("FlowFocus.Core.Models.PriorityEscalation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EscalationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApplied")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastChangesOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetPriorityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TargetPriorityId");

                    b.HasIndex("TaskId");

                    b.ToTable("PriorityEscalations");
                });

            modelBuilder.Entity("FlowFocus.Core.Models.PriorityLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastChangesOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Priorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#FF4444",
                            LastChangesOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Критический",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "#FF8C00",
                            LastChangesOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Высокий",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            Color = "#FFD700",
                            LastChangesOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Средний",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            Color = "#4CAF50",
                            LastChangesOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Низкий",
                            Order = 4
                        },
                        new
                        {
                            Id = 5,
                            Color = "#2196F3",
                            LastChangesOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Фоновый",
                            Order = 5
                        });
                });

            modelBuilder.Entity("FlowFocus.Core.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastChangesOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("FlowFocus.Core.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualAssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Complexity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EffectivePriorityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideUnderSpoiler")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Interest")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastChangesOn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PriorityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecurrenceInterval")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecurrenceSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecurrenceType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecurrenceWeekDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UserAssignedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EffectivePriorityId");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex("PriorityId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("FlowFocus.Core.Models.TaskRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastChangesOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceTaskId");

                    b.HasIndex("TargetTaskId");

                    b.ToTable("TaskRelations");
                });

            modelBuilder.Entity("FlowFocus.Core.Models.TaskTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskTags");
                });

            modelBuilder.Entity("FlowFocus.Core.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoDistributeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyComplexityLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyTaskLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyTimeLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayStartHour")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultPriorityId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideTaskTitlesDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastChangesOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoDistributeEnabled = false,
                            DailyComplexityLimit = 100,
                            DailyTaskLimit = 10,
                            DailyTimeLimit = 480,
                            DayStartHour = 5,
                            HideTaskTitlesDefault = false,
                            IsDarkMode = true,
                            LastChangesOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FlowFocus.Core.Models.PriorityEscalation", b =>
                {
                    b.HasOne("FlowFocus.Core.Models.PriorityLevel", "TargetPriority")
                        .WithMany()
                        .HasForeignKey("TargetPriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowFocus.Core.Models.TaskItem", "Task")
                        .WithMany("PriorityEscalations")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetPriority");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("FlowFocus.Core.Models.TaskItem", b =>
                {
                    b.HasOne("FlowFocus.Core.Models.PriorityLevel", "EffectivePriority")
                        .WithMany()
                        .HasForeignKey("EffectivePriorityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlowFocus.Core.Models.TaskItem", "ParentTask")
                        .WithMany("Subtasks")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FlowFocus.Core.Models.PriorityLevel", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EffectivePriority");

                    b.Navigation("ParentTask");

                    b.Navigation("Priority");
                });

            modelBuilder.Entity("FlowFocus.Core.Models.TaskRelation", b =>
                {
                    b.HasOne("FlowFocus.Core.Models.TaskItem", "SourceTask")
                        .WithMany("Relations")
                        .HasForeignKey("SourceTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowFocus.Core.Models.TaskItem", "TargetTask")
                        .WithMany("InverseRelations")
                        .HasForeignKey("TargetTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceTask");

                    b.Navigation("TargetTask");
                });

            modelBuilder.Entity("FlowFocus.Core.Models.TaskTag", b =>
                {
                    b.HasOne("FlowFocus.Core.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowFocus.Core.Models.TaskItem", "Task")
                        .WithMany("Tags")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("FlowFocus.Core.Models.TaskItem", b =>
                {
                    b.Navigation("InverseRelations");

                    b.Navigation("PriorityEscalations");

                    b.Navigation("Relations");

                    b.Navigation("Subtasks");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
