// <auto-generated />
using System;
using FlowFocus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowFocus.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("FlowFocus.Core.Models.Dependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConditionParameters")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceTaskId");

                    b.HasIndex("TargetTaskId");

                    b.ToTable("Dependencies", t =>
                        {
                            t.HasCheckConstraint("CK_Dependency_SelfReference", "SourceTaskId != TargetTaskId");
                        });
                });

            modelBuilder.Entity("FlowFocus.Core.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalculatedPriority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Complexity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("EstimatedHours")
                        .HasColumnType("REAL");

                    b.Property<int>("Interest")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PlannedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserPriority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlannedDate");

                    b.HasIndex("Status");

                    b.HasIndex("UserPriority");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("FlowFocus.Core.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoRecalculateOnAdd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyComplexityLimit")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DailyTimeLimit")
                        .HasColumnType("REAL");

                    b.Property<int>("DayStartHour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PriorityBoostDates")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowFavorites")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoRecalculateOnAdd = true,
                            DailyComplexityLimit = 50,
                            DailyTimeLimit = 8.0,
                            DayStartHour = 6,
                            ShowFavorites = true
                        });
                });

            modelBuilder.Entity("FlowFocus.Core.Models.Dependency", b =>
                {
                    b.HasOne("FlowFocus.Core.Models.TaskItem", "SourceTask")
                        .WithMany("Dependencies")
                        .HasForeignKey("SourceTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowFocus.Core.Models.TaskItem", "TargetTask")
                        .WithMany("DependentTasks")
                        .HasForeignKey("TargetTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceTask");

                    b.Navigation("TargetTask");
                });

            modelBuilder.Entity("FlowFocus.Core.Models.TaskItem", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("DependentTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
